### ISSUE TITLE
Install ortmodule got  `error: unsupported option --use_fast_math`

### ISSUE THREAD

**Issue by Rui-Ren** [microsoft/onnxruntime#12290]
**Describe the bug**

Hi there, 

I am trying to install onnxruntime_training, and I followed below steps:
- `python -m pip install --pre onnxruntime-training -f https://download.onnxruntime.ai/onnxruntime_nightly_rocm52.html`
- `python -m onnxruntime.training.ortmodule.torch_cpp_extensions.install`

However, I got the error from `python -m onnxruntime.training.ortmodule.torch_cpp_extensions.install`
```
clang-14: error: unsupported option '--use_fast_math'
```
traceback for Singularity as follows,

```
/opt/rocm/bin/hipcc -I/opt/conda/lib/python3.7/site-packages/torch/include -I/opt/conda/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/opt/conda/lib/python3.7/site-packages/torch/include/TH -I/opt/conda/lib/python3.7/site-packages/torch/include/THC -I/opt/conda/lib/python3.7/site-packages/torch/include/THH -I/opt/rocm/include -I/opt/rocm/miopen/include -I/opt/conda/include/python3.7m -c /home/aiscuser/.local/lib/python3.7/site-packages/onnxruntime/training/ortmodule/torch_cpp_extensions/hip/fused_ops/multi_tensor_adam.hip -o build/temp.linux-x86_64-3.7/home/aiscuser/.local/lib/python3.7/site-packages/onnxruntime/training/ortmodule/torch_cpp_extensions/hip/fused_ops/multi_tensor_adam.o -fPIC -D__HIP_PLATFORM_HCC__=1 -DUSE_ROCM=1 -DCUDA_HAS_FP16=1 -D__HIP_NO_HALF_OPERATORS__=1 -D__HIP_NO_HALF_CONVERSIONS__=1 -lineinfo -O3 --use_fast_math -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1013\" -DTORCH_EXTENSION_NAME=fused_ops -D_GLIBCXX_USE_CXX11_ABI=1 --amdgpu-target=gfx900 --amdgpu-target=gfx906 --amdgpu-target=gfx908 --amdgpu-target=gfx90a --amdgpu-target=gfx1030 -fno-gpu-rdc -std=c++14
clang-14: error: unsupported option '--use_fast_math'
clang-14: warning: -lineinfo: 'linker' input unused [-Wunused-command-line-argument]
error: command '/opt/rocm/bin/hipcc' failed with exit code 1
There was an error compiling 'fused_ops' PyTorch CPP extension

```

FYI,  on 7/21/2022, I did not see this error, it can be successfully installed

**Urgency**
This happens for  `onnxruntime_training=1.12.0`

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux
- Python version: 3.8
- Visual Studio version (if applicable): 
- GCC/Compiler version (if compiling from source):
- GPU TYPE:  ROCM52

**To Reproduce**
- Create a Singularity or ROCM machine
- `python -m pip install --pre onnxruntime-training -f https://download.onnxruntime.ai/onnxruntime_nightly_rocm52.html`
- `python -m onnxruntime.training.ortmodule.torch_cpp_extensions.install`

**Expected behavior**
Can anyone take a look into this? Thank you very much.

**Traceback**
From my pipeline:
```
Traceback (most recent call last):
  File "/opt/conda/envs/lib/python3.8/site-packages/onnxruntime/training/ortmodule/torch_cpp_extensions/cuda/fused_ops/setup.py", line 25, in <module>
    setup(
  File "/opt/conda/envs/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/opt/conda/envs/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/opt/conda/envs/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/opt/conda/envs/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/opt/conda/envs/lib/python3.8/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/opt/conda/envs/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/opt/conda/envs/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/opt/conda/envs/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/opt/conda/envs/lib/python3.8/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/opt/conda/envs/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 742, in build_extensions
    build_ext.build_extensions(self)
  File "/opt/conda/envs/lib/python3.8/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/opt/conda/envs/lib/python3.8/distutils/command/build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "/opt/conda/envs/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 202, in build_extension
    _build_ext.build_extension(self, ext)

```

Thank you very much in advance.

**Comment by baijumeswani** [comment]
This should not happen for rocm version of onnxruntime. Is it possible that the package is a cuda package and not a rocm one?
Are you able to run this command:
```py
python -c "from onnxruntime.capi import build_and_package_info as ort_info; print(ort_info.rocm_version)"
```
Also try to run
```py
python -c "from onnxruntime.capi import build_and_package_info as ort_info; print(ort_info.cuda_version)"
```

**Comment by Rui-Ren** [comment]
Hi @baijumeswani, thanks for your quick reply,

ran
```
python -c "from onnxruntime.capi import build_and_package_info as ort_info; print(ort_info.rocm_version)"
```
I got error of `RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd`

```
python -c "from onnxruntime.capi import build_and_package_info as ort_info; print(ort_info.cuda_version)"
```
I got the error of 
```
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
10.2
```

**Comment by ytaous** [comment]
can u check your numpy version? upgrade it and retry? 
Which docker image you are using? platform one? can u also try "ptebic.azurecr.io/internal/azureml/aifx/stable-ubuntu2004-rocm52-py38-torch1110:latest" - this one already has the nightly installed.

**Comment by Rui-Ren** [comment]
Hi @ytaous I upgraded the numpy version and got the same error.

I am using the platform one, with `pytorch==1.11.0 and rocm52`. 

Below I think image is released with onnxruntime==1.11.1 
`ptebic.azurecr.io/internal/azureml/aifx/stable-ubuntu2004-rocm52-py38-torch1110:latest` 

However, yesterday we released the onnxruntime==1.12.0, if that caused this failure?

Thank you very much for your response.

**Comment by ytaous** [comment]
you can uninstall 1.11.1 and try again with the two steps above, do u still have the same error?

**Comment by ytaous** [comment]
This issue was from the latest version of onnxruntime-training:

python -m pip install --pre onnxruntime-training== -f https://download.onnxruntime.ai/onnxruntime_nightly_rocm52.html
Looking in links: https://download.onnxruntime.ai/onnxruntime_nightly_rocm52.html
ERROR: Could not find a version that satisfies the requirement onnxruntime-training== (from versions: 1.8.0, 1.8.1, 1.9.0, 1.11.0, 1.11.1, 1.12.0.dev20220706003+rocm52, 1.12.0.dev20220707005+rocm52, 1.12.0.dev20220710001+rocm52, 1.12.0.dev20220711001+rocm52, 1.12.0.dev20220712001+rocm52, 1.12.0.dev20220713001+rocm52, 1.12.0.dev20220714001+rocm52, 1.12.0.dev20220715001+rocm52, 1.12.0.dev20220715002+rocm52, 1.12.0.dev20220718002+rocm52, 1.12.0.dev20220719002+rocm52, 1.12.0.dev20220720003+rocm52, 1.12.0.dev20220721001+rocm52, 1.12.0)
ERROR: No matching distribution found for onnxruntime-training==

pip seems to think 1.12.0 is a later version compared to 1.12.0.dev20220721 and pip downloaded the 1.12.0 version from PyPI. which is not a rocm package (it is a cuda package 1.12.0+cu10.2).

This issue will be solved by updating the master branch with VERSION_NUMBER == 1.13.0,  and this PR above will fix this issue.
