### ISSUE TITLE
Zero Result with DirectML Execution Provider

### ISSUE THREAD

**Issue by deischi** [microsoft/onnxruntime#13545]
### Describe the issue

Runing a specific 3D-segmentation network with the DirectML execution provider often gives only zero values in the result.
Network with dummy weights and example program is available here: [https://github.com/deischi/share](https://github.com/deischi/share)

The example program prints the min/max value of the output tensor: 255/14397 in good case, 0/0 in bad case.

### To reproduce

Use GPU memory by a another progam - I will see to update the test program to do that additional step.

Open RunOnnx\RunOnnx.sln from [https://github.com/deischi/share](https://github.com/deischi/share) and run.
Last line of the output is either `min/max: 255/14397` when running successfully, or `min/max: 0/0` in error case.

On my test system with an mobile RTX 3000 it is enough to use 1 GB by other programs to reliably see the problem.

### Platform

Windows

### OS Version

20H2

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.13.1

### ONNX Runtime API

C++

### Architecture

X64

### Execution Provider

DirectML

### Execution Provider Library Version

DirectML 1.9.1

**Comment by deischi** [comment]
For me this looks familiar to #11007

**Comment by sumitsays** [comment]
@deischi We are looking into it. Can you please provide us the exact driver version/date you are using for RTX 3000?

**Comment by deischi** [comment]
Driver Version: 517.40
Windows Version: 20H2 (19042.2006)

Thanks for taking a look at this.

**Comment by nums11** [comment]
Updating to onnxruntime 1.15.0 and DirectML 1.12.0 should fix the access violation errors. Can you try this and check the results?

**Comment by deischi** [comment]
After upgrading to Onnxruntime 1.15.0 and DirectML1.12.0
- CPU execution provider is working again. thanks.
- DirectML on the T1000 is still giving a zero-result, without any error mesage.

**Comment by smk2007** [comment]
Hi,

Using the latest version of ORT, I was unable to reproduce the error on NVIDIA hardware, including the T1000 8GB (Driver Version: 31.0.15.2748).

Can you confirm that the error repros on the current version of ORT 1.16 and with the latest NVIDIA drivers?
If the repro is still ongoing, can you share the OS, graphics card and driver version that shows the issue?

Thanks!

**Comment by deischi** [comment]
Upgrading to the latest version of ORT and nVidia drivers gave mixed results for me.

On my Laptop (RTX 3000) - after upgrading ORT the issue was present but after additionally upgrading the nVidia driver (537.42), the issue no longer occured.

But unfortunately on the T1000 4GB the issue still is happening.

The output of the run: [run.txt](https://github.com/microsoft/onnxruntime/files/12793562/run.txt)
nVidia driver: 537.42. all Details: [nvidia.smi.txt](https://github.com/microsoft/onnxruntime/files/12793579/nvidia.smi.txt)
OS version: Windows 10 21H2 (19044.3448)

I will see to find a T1000 8GB the next days, to test on that also.

**Comment by crahrig** [comment]
@deischi did you find an 8 GB version of the T1000 to test on too?

**Comment by deischi** [comment]
On our device, also with the T1000 8GB version the issue is still happening.
I have tried with nVidia drivers 535.98  and 537.42 - same results.

As you can see in the nvidia.smi.txt file above, our hardware configuration is a bit special. We habe two nVidia GPUs, one in TCC mode, one in WDDM mode. Hopefully that is not part of the issue.

Finally, possibly related to this issue When I try to run the model on the Intel GPU of my laptop (Intel UHD P630), it fails almost immediately with an error message:
`onnxruntime: Non-zero status code returned while running DmlFusedNode_0_0 node. Name:'DmlFusedNode_0_0' Status Message: D:\a\_work\1\s\onnxruntime\core\providers\dml\DmlExecutionProvider\src\FusedGraphKernel.cpp(365)\onnxruntime.dll!00007FFA610088D6: (caller: 00007FFA61006C35) Exception(2) tid(31ec) 887A0005 The GPU device instance has been suspended. Use GetDeviceRemovedReason to determine the appropriate action.
`

**Comment by grahameth** [comment]
I'm having a very similar issue. I too am using DirectML, use a 3D-segmentation model and see zero-results when the gpu memory is getting low. I can also try to provide detailled reproduction steps if desired. Is there any hope of getting this fixed?
