### ISSUE TITLE
TensorRT error for nested graph w/ control-flow and optional input (regression)

### ISSUE THREAD

**Issue by laggui** [microsoft/onnxruntime#16217]
### Describe the issue

I have a model with 3 subgraph paths based on input conditions. The model has multiple inputs, the first of which is optional. The other condition is based on the value of another input >= 0.

The model executes just fine on CPU and CUDA, but fails to execute with the TensorRT EP.

The original model is more complex, but I've attached a MWE with simple operations that reproduces the same behavior.

Note that the same model and MWE below actually execute fine with ORT 1.12.1 + TensorRT 8.4.1.5. But when I upgraded to ORT 1.13 and even up to the latest 1.15 release, the model fails with the error below. So technically this is a regression (?).

```
[NestedOptional] Testing w/ use_trt=False
[NestedOptional] Success!
[NestedOptional] Testing w/ use_trt=True
2023-06-02 07:58:29.795259774 [E:onnxruntime:, inference_session.cc:1644 operator()] Exception during initialization: /onnxruntime_src/onnxruntime/core/providers/tensorrt/tensorrt_execution_provider.cc:1352 SubGraphCollection_t onnxruntime::TensorrtExecutionProvider::GetSupportedList(SubGraphCollection_t, int, int, const onnxruntime::GraphViewer&, bool*) const graph_build.Resolve().IsOK() was false.

Traceback (most recent call last):
  File "/workspace/ort_inference/python/nested_opt_mwe.py", line 264, in <module>
    test_nested_optional_greater_or_equal(use_trt=True)
  File "/workspace/ort_inference/python/nested_opt_mwe.py", line 240, in test_nested_optional_greater_or_equal
    session = ort.InferenceSession(
  File "/home/prime/miniconda3/envs/ort115/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 383, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/home/prime/miniconda3/envs/ort115/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 435, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Exception during initialization: /onnxruntime_src/onnxruntime/core/providers/tensorrt/tensorrt_execution_provider.cc:1352 SubGraphCollection_t onnxruntime::TensorrtExecutionProvider::GetSupportedList(SubGraphCollection_t, int, int, const onnxruntime::GraphViewer&, bool*) const graph_build.Resolve().IsOK() was false.
```

### To reproduce

```py
from copy import deepcopy
from typing import Optional, Sequence, Tuple

import numpy as np
import onnxruntime as ort
from onnx import (
    ModelProto,
    NodeProto,
    TensorProto,
    ValueInfoProto,
    checker,
    helper,
)


def make_vi_like(vi: ValueInfoProto, name: str) -> ValueInfoProto:
    """Makes a copy of `vi` with a new name."""
    new_vi = deepcopy(vi)
    new_vi.name = name
    return new_vi


def make_optional_tensor_value_info(
    name: str, elem_type: int, shape: Sequence[int]
) -> ValueInfoProto:
    """Makes a `ValueInfoProto` with optional type."""
    tensor_type_proto = helper.make_tensor_type_proto(
        elem_type=elem_type,
        shape=shape,
    )
    opt_type_proto = helper.make_optional_type_proto(tensor_type_proto)

    vi = helper.make_tensor_value_info(name, elem_type, shape)
    vi.type.CopyFrom(opt_type_proto)
    return vi


def make_optional_vi(vi: ValueInfoProto, name: Optional[str] = None) -> ValueInfoProto:
    """Makes a copy of `vi` with optional type."""
    name = name or vi.name + ".opt"
    vi_type = vi.type.tensor_type
    vi_shape = [d.dim_param if d.dim_param else d.dim_value for d in vi_type.shape.dim]
    opt_vi = make_optional_tensor_value_info(name, vi_type.elem_type, vi_shape)
    return opt_vi


def make_const(
    vi: ValueInfoProto, name: str, value: int = 0
) -> Tuple[ValueInfoProto, NodeProto, TensorProto]:
    """Creates a constant 1D tensor from `vi`."""
    const_vi = make_vi_like(vi, name)
    const_shape = [d.dim_value for d in vi.type.tensor_type.shape.dim]
    const_shape_tensor = helper.make_tensor(
        f"{name}.shape", TensorProto.INT64, [len(const_shape)], const_shape
    )
    const_fill = helper.make_tensor(
        f"{name}.const.value", const_vi.type.tensor_type.elem_type, [1], [value]
    )
    const_node = helper.make_node(
        "ConstantOfShape",
        inputs=[const_shape_tensor.name],
        outputs=[const_vi.name],
        name=f"ConstantOfShape.{name}",
        value=const_fill,
    )
    return const_vi, const_node, const_shape_tensor


def make_opt_nested_greater_or_equal() -> ModelProto:
    """
    Creates a nested graph with (`optional(x1)`, `x2`, x3`) tensor inputs.

    `x3` is similar to an optional input with default value of -1.
    """
    # Inputs/outputs
    x1_vi = helper.make_tensor_value_info("x1", TensorProto.FLOAT, [1, 2])
    x2_vi = helper.make_tensor_value_info("x2", TensorProto.FLOAT, [1, 2])
    x3_vi = helper.make_tensor_value_info("x3", TensorProto.FLOAT, [1])
    y_vi = helper.make_tensor_value_info("y", TensorProto.FLOAT, [1, 2])
    opt_x1_vi = make_optional_vi(x1_vi, name="x1.opt")

    # Add `x1` and `x2` subgraph
    y1_vi = make_vi_like(y_vi, "x1.add.x2")
    input_get_elem_node = helper.make_node(
        "OptionalGetElement",
        inputs=[opt_x1_vi.name],
        outputs=[x1_vi.name],
        name="OptionalGetElement.Input",
    )
    add_node = helper.make_node(
        "Add", inputs=[x1_vi.name, x2_vi.name], outputs=[y1_vi.name], name="Add_Op"
    )
    add_x1_x2_subgraph = helper.make_graph(
        [input_get_elem_node, add_node],
        name="add-x1-x2-subgraph",
        inputs=[],
        outputs=[y1_vi],
        value_info=[opt_x1_vi, x1_vi, x2_vi],
    )

    # Add `x2` and const subgraph
    y2_vi = make_vi_like(y_vi, "x2.add.const")
    const_vi, const_node, const_shape_tensor = make_const(x1_vi, "x1.const", value=1)
    add_const_node = helper.make_node(
        "Add",
        inputs=[const_vi.name, x2_vi.name],
        outputs=[y2_vi.name],
        name="Add_Const",
    )
    add_x2_const_subgraph = helper.make_graph(
        [const_node, add_const_node],
        name="add-x2-const-subgraph",
        inputs=[],
        outputs=[y2_vi],
        value_info=[const_vi, x2_vi],
        initializer=[const_shape_tensor],
    )

    # Add `x3` and const subgraph
    add_const_out_vi = make_vi_like(x3_vi, "out.1")
    y3_vi = make_vi_like(y_vi, "x3.add.const")
    const_vi, const_node, const_shape_tensor = make_const(x3_vi, "x3.const", value=2)
    add_const_node = helper.make_node(
        "Add",
        inputs=[const_vi.name, x3_vi.name],
        outputs=[add_const_out_vi.name],
        name="Add_Const.1",
    )
    expand_shape = helper.make_tensor(
        f"{add_const_out_vi}.shape", TensorProto.INT64, [2], [1, 2]
    )
    expand_node = helper.make_node(
        "Expand",
        inputs=[add_const_out_vi.name, expand_shape.name],
        outputs=[y3_vi.name],
        name="Expand.out",
    )
    add_x3_const_subgraph = helper.make_graph(
        [const_node, add_const_node, expand_node],
        name="add-x3-const-subgraph",
        inputs=[],
        outputs=[y3_vi],
        value_info=[x3_vi, const_vi, add_const_out_vi],
        initializer=[const_shape_tensor, expand_shape],
    )

    # Subgraph flow based on `x3` value
    y3_if_vi = make_vi_like(y_vi, "x3.if.out")
    x3_eq_vi, x3_const_node, x3_const_shape_tensor = make_const(
        x3_vi, "x3.equal", value=0
    )
    x3_ge_vi = helper.make_tensor_value_info(
        "x3_ge",
        TensorProto.BOOL,
        shape=[1],
    )
    x3_ge_node = helper.make_node(
        "GreaterOrEqual",
        inputs=[x3_vi.name, x3_eq_vi.name],
        outputs=[x3_ge_vi.name],
        name="GreaterOrEqual.Target",
    )
    x3_has_elem_vi = helper.make_tensor_value_info(
        "x3_has_elem",
        TensorProto.BOOL,
        shape=[],  # scalar
    )
    x3_has_elem_node = helper.make_node(
        "Squeeze",
        inputs=[x3_ge_vi.name],
        outputs=[x3_has_elem_vi.name],
        name="Squeeze.x3",
    )
    if_input_node = helper.make_node(
        "If",
        inputs=[x3_has_elem_vi.name],  # condition
        outputs=[y3_if_vi.name],
        name="If.OptionalHasElement.x3",
        then_branch=add_x3_const_subgraph,
        else_branch=add_x2_const_subgraph,
    )
    x3_subgraph = helper.make_graph(
        [x3_const_node, x3_ge_node, x3_has_elem_node, if_input_node],
        name="x3-subgraph",
        inputs=[],
        outputs=[y3_if_vi],
        value_info=[x3_vi, x3_eq_vi, x3_ge_vi, x3_has_elem_vi],
        initializer=[x3_const_shape_tensor],
    )

    # Construct main graph
    x1_has_elem_vi = helper.make_tensor_value_info(
        "x1_has_elem",
        TensorProto.BOOL,
        shape=[],  # scalar
    )
    x1_has_elem_node = helper.make_node(
        "OptionalHasElement",
        inputs=[opt_x1_vi.name],
        outputs=[x1_has_elem_vi.name],
        name="OptionalHasElement.x1",
    )
    if_input_node = helper.make_node(
        "If",
        inputs=[x1_has_elem_vi.name],  # condition
        outputs=[y_vi.name],
        name="If.OptionalHasElement.x1",
        then_branch=add_x1_x2_subgraph,
        else_branch=x3_subgraph,
    )
    graph = helper.make_graph(
        [x1_has_elem_node, if_input_node],
        "opt-graph",
        [opt_x1_vi, x2_vi, x3_vi],
        [y_vi],
        value_info=[x1_has_elem_vi],
    )

    m = helper.make_model(
        graph,
        opset_imports=[
            helper.make_opsetid("", 15),
        ],
    )

    checker.check_model(m, full_check=True)

    return m


def test_nested_optional_greater_or_equal(use_trt: bool = False) -> None:
    print(f"[NestedOptional] Testing w/ use_trt={use_trt}")
    m = make_opt_nested_greater_or_equal()

    providers = ["CUDAExecutionProvider"]
    if use_trt:
        providers.insert(0, "TensorrtExecutionProvider")
    session = ort.InferenceSession(
        m.SerializeToString(),
        providers=providers,
    )

    x1_name, x2_name, x3_name = [i.name for i in m.graph.input]
    session.run(
        [m.graph.output[0].name],
        {
            x1_name: None,
            x2_name: np.ones((1, 2), dtype=np.float32),
            x3_name: np.array([-1], dtype=np.float32),
        },
    )

    print("[NestedOptional] Success!")
    return


if __name__ == "__main__":
    # Remove CleanUnusedInitializersAndNodeArgs warnings
    # ort.set_default_logger_severity(3)

    test_nested_optional_greater_or_equal(use_trt=False)
    test_nested_optional_greater_or_equal(use_trt=True)
```

### Urgency

We're upgrading our dependencies for our app at this time, the sooner the better.

### Platform

Linux

### OS Version

Ubuntu 20.04.2 LTS

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.15

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

TensorRT

### Execution Provider Library Version

TensorRT 8.6

**Comment by chilo-ms** [comment]
Thanks for raising this issue, let me try to repro and investigate this.

**Comment by chilo-ms** [comment]
Hi @laggui,

I took a look at the model, it's a three-layers control flow op ("if" node in this case) model. 

For ORT 1.12 and before, the control flow node itself will be placed on CUDA EP and the control flow node's subgraphs will be place on TRT EP. If you enabled verbose log you can see the nodes placement and ORT TRT can successfully run it.

Started from ORT 1.13, we fixed some [issues](https://github.com/microsoft/onnxruntime/pull/12692) to make all the control flow node as well as its subgraphs all be placed on TRT EP, and it can run the model with two-level control flow op models and simple nested control flow op models. However we haven't fixed the issue of nested control flow op case where the input is defined in the main level and consumed by the third level or deeper level. This is also the case of your model. Due to ORT uses bottom-up approach to handle subgraphs level by level, it requires more logic to check and generate the valid graph.
I had a [dev branch](https://github.com/microsoft/onnxruntime/tree/chi/trt_nested_control_flow_op) to fix this issue and it's time to revisit it. Will create a PR to fix this.

**Comment by laggui** [comment]
@chilo-ms yeah I noticed some subgraph operations were dispatched differently between both EPs.

Will wait for your PR fix :)
Thanks!

**Comment by chilo-ms** [comment]
Hi @laggui,

Here is the PR https://github.com/microsoft/onnxruntime/pull/16343, if you have time, could you help test with the real model? I run the test you shared, and it can successfully run it now.

**Comment by laggui** [comment]
Hi @chilo-ms, I can confirm that the MWE I shared works with your changes.

However, the real model still fails. As you can image it's a bit more complex than the example.
Would it be possible to share that model in private?

**Comment by chilo-ms** [comment]
Re: Would it be possible to share that model in private?
My email is Chi.Lo@microsoft.com and you can put your model on whatever space on internet and send the link to me?

**Comment by laggui** [comment]
Thanks for sharing! I'll send you the info tomorrow first thing in the morning :)

**Comment by chilo-ms** [comment]
@laggui, I found the issue and updated the PR. It can now run the model from my side, could you help test from your side?

**Comment by laggui** [comment]
@chilo-ms Hmmm still getting the same error on my end. I'm using the exact model and script I shared, just rebuilt the python wheel from scratch.

Maybe something else differs on my side?

**Comment by chilo-ms** [comment]
I shared the wheel file with you. Also, what is your build command and test log from your side?

**Comment by laggui** [comment]
I can confirm, everything works on my end as well with the build from your branch! Thanks for your work :)
