### ISSUE TITLE
Yolo v3 inference 100x slower than expected

### ISSUE THREAD

**Issue by brantPTS** [microsoft/onnxruntime#1961]
**Describe the bug**
Running an inference with the Yolov3 model from onnx model zoo is 100x slower than expected. The original paper estimates inference time of 22 ms. Using CUDA onnx runtime takes around 2 seconds. 

**Urgency**
We are blocked from using the ONNX runtime until this is fixed

**System information**
- OS Platform and Distribution: Windows 10 Pro
- ONNX Runtime installed from source (built locally with Sep 27, 2019 source code)
- Visual Studio version (if applicable): 2019
- CUDA/cuDNN version: 10.0 / 7.3
- GPU model and memory: nVidia GTX 1080ti

**To Reproduce**
Get latest source code (or Sep 27 version, if not reproduced)
Build locally with cuda similar to: 
.\build.bat --msvc_toolset 14.11 --use_cuda --cuda_home "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0" --cudnn_home C:\local\cudnn-7.3\cuda --build_csharp 

Download yolov3 model from onnx model zoo, and ensure files on disk here (or alter source code in unit test appropriately if files in different location): 
D:\modelsyolov3\yolov3\yolov3.onnx
D:\modelsyolov3\yolov3\test_data_set_0\input_0.pb

Open the following solution in VS 2019: 
C:\local\onnx\onnxruntime\csharp\OnnxRuntime.CSharp.sln
Add a unit test (see code below) and run in debug mode:
C:\local\onnx\onnxruntime\csharp\test\Microsoft.ML.OnnxRuntime.Tests\InferenceTest.cs
Look at debug output to see median run time. Running with GPU takes around 2 seconds, running with CPU takes around 16 seconds. 

The unit test code to add to InferenceTest.cs: 

```
[Fact]
private void mytest()
{
	var modelsDir = @"D:\modelsyolov3";
	var modelRoot = new DirectoryInfo(Path.Combine(modelsDir));
	foreach (var modelDir in modelRoot.EnumerateDirectories())
	{
		var onnxModelNames = modelDir.GetFiles("*.onnx");
		var onnxModelFileName = Path.Combine(modelsDir, modelDir.Name, onnxModelNames[0].Name);
		SessionOptions opts = new SessionOptions();
		//SessionOptions opts = SessionOptions.MakeSessionOptionWithCudaProvider(0);
		using (var session = new InferenceSession(onnxModelFileName, opts))
		{
			var testRoot = new DirectoryInfo(Path.Combine(modelsDir, modelDir.Name));
			var testData = testRoot.EnumerateDirectories("test_data*").First();

			//// Load test data
			var testDataFile = Path.Combine(modelsDir, modelDir.Name, testData.ToString(), "input_0.pb");
			var dataIn = LoadTensorFromFilePb(testDataFile);

			///// Create Inputs
			var nov = new List<NamedOnnxValue>();
			nov.Add(
				NamedOnnxValue.CreateFromTensor<float>
					("input_1", new DenseTensor<float>(dataIn, new int[] { 1, 3, 416, 416 })));
			nov.Add(
				NamedOnnxValue.CreateFromTensor<float>
					("image_shape", new DenseTensor<float>(new float[] { 416, 416 }, new int[] { 1, 2 })));

			int count = 5;
			List<double> timesMs = new List<double>(count);
			Stopwatch sw = new Stopwatch();

			for (int i = 0; i < count; i++)
			{

				sw.Restart();
				///// Run Session
				using (var resnov = session.Run(nov))
				{
					timesMs.Add(sw.ElapsedMilliseconds);
					var res = resnov.ToArray()[0].AsTensor<float>().ToArray<float>();
				}
			}
			timesMs.Sort();
			double medianTime = timesMs[count / 2];
			Console.Out.WriteLine($"Median time: {medianTime:0.00} ms");
			Debug.WriteLine($"Median time: {medianTime:0.00} ms");

		}
	} //model
}
````

**Expected behavior**
On a GTX 1080ti GPU, inference should be less than 20ms

**Comment by ybrnathan** [comment]
On GTX 1050 GPU, I got around 170ms. The major reason of bad performance is some Conv node of this model falls back to CPU. The reason of the fallback is because ORT relies on CuDnn for Conv, and CuDnn conv does not support asymmetric padding like (1,1,0,0).

**Comment by brantPTS** [comment]
@ybrnathan , would you please clarify? I.e., did you run my unit test example above and get a median time of 170ms? Can you suggest a fix for running yolov3 on the ONNX runtime? 
Thanks!

**Comment by ybrnathan** [comment]
When you build from source, you need to build a release version (seems like you are building a debug version) by adding --config Release.

Once you are done, you can find a perf test tool under build\Windows\Release\Release\onnxruntime_perf_test.exe. Given YoloV3 has its test data, you can just run this tool to get the performance number:

onnxruntime_perf_test.exe -t 10 -e cuda onnx_model_file_path .\output.txt.

**Comment by brantPTS** [comment]
@ybrnathan  Thank you, I ran the same unit test above in Release mode and got 128ms median time. I'm a bit shocked the release version was that much faster, so clearly this is a big step in the right direction.  The inference time is still probably 10x slower than it should be for yolov3 on a 1080ti, though. Can you suggest how to avoid reverting to CPU for conv?

**Comment by ybrnathan** [comment]
There are about 5 Conv operators fall back to CPU, which introduces CPU-GPU sync. Asymmetric Padding is a known issue and requires ONNX Runtime Cuda Kernel change. It's in the backlog but I do not expect it will be ready in short term. Please stay tuned.

**Comment by brantPTS** [comment]
@ybrnathan , Thank you again, that is very helpful information.  What's the best way to find out when Cuda Kernel change is implemented? Should I just test each release or will it be more publicized?

**Comment by ybrnathan** [comment]
Internally we are trying TensorRT to see if TensorRT execution provider could cover this model. If not, we will update this thread once the fix is merged to master.

**Comment by brantPTS** [comment]
Excellent, thanks @ybrnathan

**Comment by faxu** [comment]
Closing this issue. Please reopen and provide more details if the latest release still exhibits perf issues.

**Comment by xmba15** [comment]
@faxu 
I met the same perf problem with the latest release of onnxruntime.
I also tested on yolov3 model from onnx model zoo with C++ API.
My program is summarized in the following repository.
https://github.com/xmba15/onnx_runtime_cpp/blob/master/examples/TestObjectDetection.cpp
The speed for one inference is about 0.2[sec] for my environment with 1080 Ti.

The current release still does not support some convs:
```
2020-04-28 02:31:39.354570230 [W:onnxruntime:test, cuda_execution_provider.cc:1495 GetCapability] CUDA kernel not supported. Fallback to CPU execution provider for Op type: Conv node name: conv2d_2_0
2020-04-28 02:31:39.354645504 [W:onnxruntime:test, cuda_execution_provider.cc:1495 GetCapability] CUDA kernel not supported. Fallback to CPU execution provider for Op type: Conv node name: conv2d_5_0
2020-04-28 02:31:39.354748138 [W:onnxruntime:test, cuda_execution_provider.cc:1495 GetCapability] CUDA kernel not supported. Fallback to CPU execution provider for Op type: Conv node name: conv2d_10_0
2020-04-28 02:31:39.354836854 [W:onnxruntime:test, cuda_execution_provider.cc:1495 GetCapability] CUDA kernel not supported. Fallback to CPU execution provider for Op type: Conv node name: conv2d_27_0
2020-04-28 02:31:39.354903588 [W:onnxruntime:test, cuda_execution_provider.cc:1495 GetCapability] CUDA kernel not supported. Fallback to CPU execution provider for Op type: Conv node name: conv2d_44_0
```
I built onnxruntime from source with the following options:
```
BUILDTYPE=Release
BUILDARGS="--config ${BUILDTYPE}"
BUILDARGS="${BUILDARGS} --use_cuda --cuda_version=${CUDA_VERSION} --cuda_home=${CUDA_HOME} --cudnn_home=${CUDNN_HOME}"
BUILDARGS="${BUILDARGS} --parallel"
BUILDARGS="${BUILDARGS} --update"
BUILDARGS="${BUILDARGS} --use_openmp"
BUILDARGS="${BUILDARGS} --cmake_extra_defines CMAKE_INSTALL_PREFIX=${INSTALL_PREFIX}"
```
@ybrnathan @faxu 
Can you help clarify about this perf problem of onnxruntime?
It is a pity if I have to give up on using the lib for such perf problem.

**Comment by brantPTS** [comment]
> Closing this issue. Please reopen and provide more details if the latest release still exhibits perf issues.

@faxu , would you please re-open this issue as per @xmba15 recent test? 
Thanks,
Brant

**Comment by xmba15** [comment]
@snnn @pranavsharma
I'm sorry to disturb you...

**Comment by joba01** [comment]
please see https://github.com/microsoft/onnxruntime/issues/3414
I was able to speedup my model and get rid of asymmetric padding by postprocessing the graph, add symmetric paddings and cut away the not needed data afterwards, worked for two SSD models and brings a speedup of ~5 compared to the 'Fallback to CPU' warning (same execution times as with tensorflow gpu). Adding padding nodes also helps but only brings a speedup of ~3.

**Comment by xmba15** [comment]
Just to share my experience though. the yolov3 model in onnx model zoo if one of the reimplementation of the original yolov3, which has , more or less difference compared to the original. I have tried other yolov3 onnx from different source codes, and the performance was OK. So for those who tried to look for a way to deploy yolov3 onnx in C++, if the perf problem still persists with the latest onnxruntime version, maybe you can try another open-source implementation of yolov3.
