### ISSUE TITLE
KleidiAI library usage needs to check for SME2, not SME

### ISSUE THREAD

**Issue by john-dance** [microsoft/onnxruntime#26377]
### Describe the issue

Commit cd450d1 introduced the usage of the KleidiAI library. However, the test to enable it in platform.cpp just checks for SME, rather than SME2.

```
    if(MLAS_CPUIDINFO::GetCPUIDInfo().HasArm_SME()){
        this->MlasGemmBatchOverride = ArmKleidiAI::MlasGemmBatch;
        this->MlasGemmPackBSizeOverride = ArmKleidiAI::MlasGemmPackBSize;
        this->MlasGemmPackBOverride = ArmKleidiAI::MlasGemmPackB;
        this->MlasConvPrepareOverride = ArmKleidiAI::MlasConvPrepare;
        this->MlasConvOverride = ArmKleidiAI::MlasConv;
    }
```

This allows the library to be used on systems that support SME but not SME2, leading to illegal instructions during a run.

The newest pytorch/cpuinfo implementation has support for cpuinfo_has_arm_sme2(). https://github.com/search?q=repo%3Apytorch%2Fcpuinfo%20cpuinfo_has_arm_sme2&type=code

This needs to be added to cpuid_info.cc and exposed with a new function. Meanwhile, the default build should include "--no_kleidiai".

### To reproduce

Run a simple convolution using the CPU execution provider on a device that supports SME1, but not SME2.

### Platform

Android

### OS Version

16

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

1.23

### ONNX Runtime API

C++

### Architecture

ARM64

### Execution Provider

Default CPU

**Comment by snnn** [comment]
Oh, then I think it probably is Android and Linux only. 
Since the detection logic isn't fully implemented for the other operating systems. See https://github.com/pytorch/cpuinfo/issues/317 and https://github.com/pytorch/cpuinfo/issues/279 . Thanks @edgchen1  for pointing it out.

**Comment by patryk-kaiser-ARM** [comment]
Hi @john-dance can you apply the patch attached in this comment, it should fix the issue for you:
https://github.com/microsoft/onnxruntime/pull/26399#issuecomment-3442557132

**Comment by laurenspriem** [comment]
Any update on this issue? It's causing crashes on new devices such as OnePlus15 #26678

**Comment by chengxinping** [comment]
Any update on this issue?

**Comment by john-dance** [comment]
ORT 1.24.1 still only tests for if(MLAS_CPUIDINFO::GetCPUIDInfo().HasArm_SME())

This will lead to invalid instructions on devices that support SME but not SME2

It appears that this PR was never merged/accepted.
https://github.com/microsoft/onnxruntime/pull/26399

Could we please get the test updated to HasArm_SME2 in ORT 1.24.2?

**Comment by john-dance** [comment]
Also, we need to reopen a related issue: https://github.com/microsoft/onnxruntime/issues/26131

This error is still happening in 1.24.1 with clang compiler, targeting Linux aarch64 with a OE GCC 11.2 toolchain.

**Comment by laurenspriem** [comment]
Please also reopen #26361

This issue is causing crashes on certain devices, and it's blocking upgrades to 1.24

**Comment by patryk-kaiser-ARM** [comment]
I have opened a PR which should hopefully resolve this issue once and for all: https://github.com/microsoft/onnxruntime/pull/27403
The problem is that SME2 calls were hard coded for packing operations on DynamicQGemm.
Making use of the ukernel interface to select between SME and SME2 kernel variants fixes this problem.

**Comment by hariharans29** [comment]
@john-dance / @laurenspriem - Please let us know/ re-open if you still run into issues. If there is another patch release for 1.24, I ll include this fix. Thanks @patryk-kaiser-ARM for the fix!

**Comment by john-dance** [comment]
@hariharans29 Thank you. We are limited to using official releases, so we look forward to 1.24.3.
