### ISSUE TITLE
Android build is failing both on Windows and Linux

### ISSUE THREAD

**Issue by ShmuelFine** [microsoft/onnxruntime#2877]
I'm trying to cross compile for Android both on Windows 10 and Linux (Ubuntu 18.04), and none of them work! 
I've downloaded the protobuf last stable branch to cmake/external, and:
On windows, it builds the protobuf successfully but when it goes on, for some reason CMakeFiles\3.16.2\VCTargetsPath.vcxproj is created with  ToolsVersion="4.0" !! which I don't have and have no way to download (VS2010.... )
The cmake insisted on using NVidia NSight. Ok I installed it (though I build for android and don't intend to use Nvidia specific api but whatever). Perhaps this what forces such an old tools version?
command on windows:
build.bat --android --android_ndk_path C:\Users\Admin\AppData\Local\Android\Sdk\ndk\20.1.5948944 --android_abi arm64-v8a --android_api 27 --cmake_generator "Visual Studio 16 2019"
I tried adding --msvc_toolset 15.00 it didn't change anything.

On Linux, it says a funny thing: "unknown command /home/.../protobuf.cmake". well, indeed, it's a folder. (cmake is in the PATH)

Please help, it's quite urgent for me,
Thanks.

**Comment by kunal2197** [comment]
I facing the same issue on windows 10. When I try to build CMake insist to have Nvidia Nsight installed? Is it compulsory to have it installed though I don't want to use it in android?

build.bat --android --android_ndk_path C:\Users\Admin\AppData\Local\Android\Sdk\ndk\20.1.5948944 --android_abi arm64-v8a --android_api 26 --cmake_generator "Visual Studio 16 2019"

I was able to build an onnxruntime java package but can't use it in android. 
Can someone put exactly how can we use onnxruntime in android?
Thanks.

**Comment by snnn** [comment]
Right, currently it is failing in the master branch. 
https://github.com/microsoft/onnxruntime/runs/411725399

If you know how to fix it, welcome to submit your pull requests.  Otherwise I'll do it next month. 

Thank you

**Comment by kunal2197** [comment]
Thanks for reply @snnn . Still, one doubt, is it compulsory to have Nvidia Nsight Visual studio installed for the android build?

**Comment by snnn** [comment]
The build break is fixed

**Comment by ShmuelFine** [comment]
I'm sorry but I've just cloned and tried to build by the instructions for Andoird at the bottom of the [build instructions page](https://github.com/microsoft/onnxruntime/blob/master/BUILD.md), and it didn't work for me nor on windows or linux.
On windows it first claimed that the protobuf (cmake/externals) folder is empty, and later (after I've poured there the relevant repo) it claimed that git clone protobuf failed since the folder isn't empty (guess why... :) )
On linux (ubuntu 18.04) - again complained that protobuf is empty, and then complained that snap failed on protobuf...
Did I do something wrong?
Thanks

**Comment by ShmuelFine** [comment]
@snnn, could you please supply your building command / process?

**Comment by snnn** [comment]
git clone --recursive

Did you add this flag when doing the clone?

**Comment by ShmuelFine** [comment]
Silly me. Thanks for pointing this out. However, this does not solve the issue. Now it's the previous error I had.
on Windows: 
`git clone https://github.com/microsoft/onnxruntime.git --recursive`
Then
`build.bat --android --android_ndk_path C:\Users\Admin\AppData\Local\Android\Sdk\ndk\20.1.5948944 --android_abi arm64-v8a --android_api 27 --cmake_generator "Visual Studio 16 2019"`
Got:
`CMake Error at CMakeLists.txt:8 (project): ... to get the value of VCTargetsPath: ... onnxruntime\build\Windows\Debug\CMakeFiles\3.16.2\VCTargetsPath.vcxproj ... error MSB8020: The build tools for Visual Studio 2010 (Platform Toolset = 'v100') cannot be found.`

**Comment by ShmuelFine** [comment]
@snnn, should I look for an additional problem on my side ? everything works for you from clean clone?

**Comment by snnn** [comment]
@gwang-msft  Any thoughts?

**Comment by gwang-msft** [comment]
The new build instruction here (https://github.com/microsoft/onnxruntime/blob/master/BUILD.md#Android) lists the necessary components and steps for cross-build on Windows 10, it was recently updated (https://github.com/microsoft/onnxruntime/pull/3971)
