### ISSUE TITLE
C++ API Failing to create Tensor with dim =-1

### ISSUE THREAD

**Issue by ApluUalberta** [microsoft/onnxruntime#5271]
I am currently attempting to use the ONNX Runtime C++ API to deploy a custom network, the input is shaped as follows:
![Capture](https://user-images.githubusercontent.com/39037565/94052558-f58b8900-fd8d-11ea-8bdb-e9ddbbc85be1.PNG)

In ONNX runtime, the unk__2737 is represented as "-1" as shown here:
![Capture](https://user-images.githubusercontent.com/39037565/94052851-60d55b00-fd8e-11ea-8fbf-c64f6286aa70.PNG)

The problem is that when I try to create a tensor from these dimensions, ORT has a hard time reading in a dimension of -1:
![Capture](https://user-images.githubusercontent.com/39037565/94056748-90d32d00-fd93-11ea-8f0e-3cf87482b66e.PNG)

I have tried pre-initializing a vector with non-negative values that were the same as an image that I was putting in, but this resulted in the same error.

**Urgency**
None

**System information**
- Windows 10 64-Bit
- ONNX Runtime installed from Nuget Package Manager
- ONNX Runtime version: Version 1.4.0
- Python version: N/A -> C++
- Visual Studio version (if applicable): 2019
- GCC/Compiler version (if compiling from source): 
- CUDA/cuDNN version: 10.2 and 7.6.5
- GPU model and memory: GeForce GTX 1660 TI

**To Reproduce**
- First, The Visual Studio Project must have references to OpenCV and an integrated NuGet ONNX Runtime installed in project manager
- Must have an image to use in the same directory as the .cpp src code.
- Run the program in Debug x64.

**Expected behavior**
The code will error out once a tensor is created with the fo0llowing error:
![Capture](https://user-images.githubusercontent.com/39037565/94057206-28d11680-fd94-11ea-9bac-45a1032852e7.PNG)

**Comment by pranavsharma** [comment]
```unk__*``` are symbolic dimensions; think of them as placeholders. It means when you create an input tensor you can use any positive dimension for them.

**Comment by ApluUalberta** [comment]
> `unk__*` are symbolic dimensions; think of them as placeholders. It means when you create an input tensor you can use any positive dimension for them.

Hi there,

Thanks for the reply! I am aware that the values are read as "any positive integer", but the C++ API does not allow me to create a tensor, even if I try to hardcode the values with a picture's dimension. A good example is when I do it here: 
![Capture](https://user-images.githubusercontent.com/39037565/94064193-2a9fd780-fd9e-11ea-8d5a-49a1e3ef603c.PNG)

Even after passing in the positive dimension data, it does not create the Tensor successfully. Is tehre something I am missing?

**Comment by pranavsharma** [comment]
What error do you get when you use valid (non-negative) dimensions to create the tensor? We've a lot of tests that use this API, so this should be working.

**Comment by ApluUalberta** [comment]
At line 57 as shown, I get these highlighted error messages after running in the debugger console:
![Capture](https://user-images.githubusercontent.com/39037565/94076444-f1716280-fdb1-11ea-9923-add7531225ff.PNG)

This error remains the same even if I change the input_dimensions from ambiguous to hard-coded uint64_t types.

**Comment by pranavsharma** [comment]
> > `unk__*` are symbolic dimensions; think of them as placeholders. It means when you create an input tensor you can use any positive dimension for them.
> 
> Hi there,
> 
> Thanks for the reply! I am aware that the values are read as "any positive integer", but the C++ API does not allow me to create a tensor, even if I try to hardcode the values with a picture's dimension. A good example is when I do it here:
> ![Capture](https://user-images.githubusercontent.com/39037565/94064193-2a9fd780-fd9e-11ea-8d5a-49a1e3ef603c.PNG)
> 
> Even after passing in the positive dimension data, it does not create the Tensor successfully. Is there something I am missing?

This shows that you've 3 elements in the vector input_dims. However, the number of dims that you pass to CreateTensor (last argument) is 4. This leads to reading uninitialized memory as seen [here](https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/core/session/onnxruntime_c_api.cc#L184-L189). Reading uninitialized memory leads to undefined error. The CreateTensor API assumes you'll pass in the correct length.

**Comment by yy19931029** [comment]
you can change the dims until it become no "-1", I add 


		for (int j = 0; j < input_node_dims.size(); j++) {
			if (input_node_dims[j] == -1)
			{
				input_node_dims[j] = 1;
			}
			printf("Input %d : dim %d=%jd\n", i, j, input_node_dims[j]);
		}

in example code and solve the problem.

**Comment by pranavsharma** [comment]
Closing as per https://github.com/microsoft/onnxruntime/issues/5271#issuecomment-698189528. Reopen if this doesn't solve it.
